<?php
	require_once("includes/header.php");
?>            
<main class="container deskcontainer">
	<div class="flexible-width2">
		<div class="flex ">
			<div class="flexible-width">
				<div class="fcName">Terms & Conditions</div>
				<div class="infoDim mt20 f15N pb20 featbot">
					The GOLFWEATHER.com site is (the "Site") is owned and operated by iGlobalWeather. Listed below are the terms and conditions of use (the "Terms") for this Site. By using, accessing and/or viewing information on the Site, you (the .Participant.) agree to be bound by these Terms. Participant understands and agrees that its use of this Site is a benefit voluntarily given by GOLFWEATHER and that GOLFWEATHER may withdraw that benefit and rescind your participation at any time for any reason in its sole discretion. If you do not agree to the Terms you cannot use this Site or the services and information offered herein.
					<br /><br />
				</div>
				<div class="infoDim mt30 f15N pb20">
					<ol class="numInd">
						<li><strong class="white">PERMITTED USE</strong><br />You may use the Site and the features, information, pictures and other data contained therein (collectively, the "Data") only for personal, non-commercial purposes. You may access, view and make copies of the Data in the Site for your personal, non-commercial use and will not publish or otherwise distribute the Data for any other purpose. Without limiting the foregoing, you may not utilize the Site to sell a product or service, to advertise or direct activity to other websites or for similar commercial activities without our express written consent. You may not modify, publish, transmit, display, participate in the transfer or sale, create derivative works, or in any way exploit, any of the Data, in whole or in part. Further restrictions on the use of this Site and its Data are provided in Sections 2, 6 and 9 of these Terms.<br /><br /></li>
						<li><strong class="white">OWNERSHIP/TRADEMARKS</strong><br />Participant does not acquire or have any ownership, license or other proprietary interest in the Site or the Data. You understand that the Site and the Data are protected by copyrights, trademarks, service marks, patents and other proprietary rights and laws. You cannot use any protected material without the express written consent of the owner of such material except as permitted by law. Specifically, some of Data on this Site is unique and proprietary to GOLFWEATHER and is not available for commercial use without the advance written consent from GOLFWEATHER. ANY USE OF THIS DATA SHALL ACKNOWLEDGE GOLFWEATHER AS THE SOURCE. GOLFWEATHER will take appropriate legal action to protect and safeguard any unauthorized use of this Data.<br /><br /></li>
						<li><strong class="white">LINKS</strong><br />The Site may include links and advertisements to other websites, products or services. You acknowledge that these links are provided solely as a convenience to you and not as an endorsement by GOLFWEATHER or by any of its third-party providers regarding the content of those other websites. Neither GOLFWEATHER nor its third-party providers are responsible for or will have any liability with respect to the information contained in any websites that you may access as a result of such links including any objectionable or offensive content. If you decide to visit any other website for any reason, you do so at your own risk. <br /><br /></li>
						<li><strong class="white">ADVERTISERS/VENDORS/SERVICE PROVIDERS.</strong><br />The Site may contain advertising and sponsorship. Advertisers and sponsors are responsible for insuring that materials submitted for inclusion on the Site are accurate and comply with applicable laws. GOLFWEATHER will not be responsible for the illegality of or any error in accuracy in any advertisers, or sponsors, materials, participant understands and agrees that, in order to provide for the use of this Site, GOLFWEATHER contracts with certain vendors and service providers, which have certain rights, limitations of warranties, and limitations of liability in those contracts. Participant understands and agrees that it is not a third party beneficiary under any such agreements, that it has no rights whatsoever pursuant to such agreements, and that it has no contractual or other relationship with any advertiser, business affiliate, vendor or service provider by reason of the use or information provided on this Site or any agreement relating to the Site. To the extent that Participant has any such rights or claims by operation of law or otherwise, Participant hereby waives any and all rights and claims whatsoever against those vendors and service providers whether resulting from the exercise of any right by such vendors or service providers pursuant to such agreements, the any error or omission in the services provided, not provided, withdrawn or terminated, or the use of this Site.<br /><br /></li>
						<li><strong class="white">LIMITATION OF LIABILITY.</strong><br />GOLFWEATHER assumes no responsibility for, and shall not be liable for, any damages or expenses you may incur as a result of any inaccuracy, incompleteness or obsolescence of any Data contained in the Site. THE SERVICES OF THE SITE ARE PROVIDED .AS IS, WITH NO WARRANTIES WHATSOEVER. Without limiting the generality of the forgoing, you agree that neither GOLFWEATHER nor any of its affiliates, employees or agents will be liable to you or to any other party for any direct or indirect damages, or for any special, exemplary, punitive, incidental, consequential or other damages (including, but not limited to, lost profits or lost time), whether based on contract, tort, strict liability or otherwise, which arise out of or are in any way connected with any access to the Site or any viewing or use of any information on the Site. You acknowledge that the limitations in this Section are reasonable and appropriate. GOLFWEATHER DISCLAIMS ALL WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, CURRENCY OR RELIABILITY OF THE DATA IN THE SITE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OR OTHERWISE ARISING BY LAW OR STATUTE. YOU AGREE THAT YOUR USE OF, OR RELIANCE UPON, ALL DATA OBTAINED THROUGH THE SITE IS AT YOUR OWN DISCRETION AND RISK.<br /><br /></li>
						<li><strong class="white">INDEMNIFICATION</strong><br />You agree to indemnify and to hold GOLFWEATHER, its subsidiaries, affiliates, business partners, officers, employers and other agents, harmless from and against any loss, liability, damage or expense (including reasonable attorneys fees) arising out of your use of the Site, including, without limitation, any violations by you in the terms and conditions for your use of the Site.<br /><br /></li>
						<li><strong class="white">VIRUSES</strong><br />We will use commercially reasonable efforts to maintain the Site free of viruses and other harmful components. However, as the Site is accessible by third parties, we cannot assume any responsibility for any viruses or other harmful components that may affect your computer equipment or other property as a result of your access to, viewing of or downloading any Data from the Site. We do not warrant that the Site, its servers or any Data downloaded from the Site is free from viruses, bugs or other harmful components.<br /><br /></li>
						<li><strong class="white">MODIFICATIONS/TERMINATION</strong><br />Without limiting its other remedies, GOLFWEATHER may immediately discontinue, suspend, terminate or block your and any user's access to this Site at any time in its sole discretion. GOLFWEATHER may amend or modify these terms and conditions at any time. Any such changes will become effective immediately upon the date they are first posted to this Site. You agree to be bound by these revised terms and conditions. It is your responsibility to return to this page from time to time to review the most current terms and conditions. GOLFWEATHER does not assume any obligation to notify you of changes to these terms and conditions.<br /><br /></li>
						<li><strong class="white">ENTIRE AGREEMENT</strong><br />These terms and conditions of use for this website constitute the entire agreement between you and GOLFWEATHER regarding your access to the Site and your reproduction and use of any information in the Site. Any waiver of any term or condition shall not be effective unless in a written document signed by an authorized representative of GOLFWEATHER</li>
					</ol>
					
				</div>
			</div>
		</div>
	</div>
	<div class="fixed-width">
<?php
	require_once("includes/banners.php");
?>            
	</div>
</main>

<div class="mobidiv">
	<div class="mobiinner mBG">
		<div class="mob-banner1">
			<img src="<?php echo $dirAdj;?>img/banners/tag-heuer-mobi.jpg" class="fw" /><div id="txtmob" class="clockmob"></div>
		</div>
		<div class="f20B pt15">Terms & Conditions</div>
		<div class="mobiTxt ">
				<div class="infoDim mt20 mobiTxt pb20 featbot">
					The GOLFWEATHER.com site is (the "Site") is owned and operated by iGlobalWeather. Listed below are the terms and conditions of use (the "Terms") for this Site. By using, accessing and/or viewing information on the Site, you (the .Participant.) agree to be bound by these Terms. Participant understands and agrees that its use of this Site is a benefit voluntarily given by GOLFWEATHER and that GOLFWEATHER may withdraw that benefit and rescind your participation at any time for any reason in its sole discretion. If you do not agree to the Terms you cannot use this Site or the services and information offered herein.
					<br /><br />
				</div>
				<div class="infoDim mt30 mobiTxt pb20">
					<ol class="numInd">
						<li><strong class="white">PERMITTED USE</strong><br />You may use the Site and the features, information, pictures and other data contained therein (collectively, the "Data") only for personal, non-commercial purposes. You may access, view and make copies of the Data in the Site for your personal, non-commercial use and will not publish or otherwise distribute the Data for any other purpose. Without limiting the foregoing, you may not utilize the Site to sell a product or service, to advertise or direct activity to other websites or for similar commercial activities without our express written consent. You may not modify, publish, transmit, display, participate in the transfer or sale, create derivative works, or in any way exploit, any of the Data, in whole or in part. Further restrictions on the use of this Site and its Data are provided in Sections 2, 6 and 9 of these Terms.<br /><br /></li>
						<li><strong class="white">OWNERSHIP/TRADEMARKS</strong><br />Participant does not acquire or have any ownership, license or other proprietary interest in the Site or the Data. You understand that the Site and the Data are protected by copyrights, trademarks, service marks, patents and other proprietary rights and laws. You cannot use any protected material without the express written consent of the owner of such material except as permitted by law. Specifically, some of Data on this Site is unique and proprietary to GOLFWEATHER and is not available for commercial use without the advance written consent from GOLFWEATHER. ANY USE OF THIS DATA SHALL ACKNOWLEDGE GOLFWEATHER AS THE SOURCE. GOLFWEATHER will take appropriate legal action to protect and safeguard any unauthorized use of this Data.<br /><br /></li>
						<li><strong class="white">LINKS</strong><br />The Site may include links and advertisements to other websites, products or services. You acknowledge that these links are provided solely as a convenience to you and not as an endorsement by GOLFWEATHER or by any of its third-party providers regarding the content of those other websites. Neither GOLFWEATHER nor its third-party providers are responsible for or will have any liability with respect to the information contained in any websites that you may access as a result of such links including any objectionable or offensive content. If you decide to visit any other website for any reason, you do so at your own risk. <br /><br /></li>
						<li><strong class="white">ADVERTISERS/VENDORS/SERVICE PROVIDERS.</strong><br />The Site may contain advertising and sponsorship. Advertisers and sponsors are responsible for insuring that materials submitted for inclusion on the Site are accurate and comply with applicable laws. GOLFWEATHER will not be responsible for the illegality of or any error in accuracy in any advertisers, or sponsors, materials, participant understands and agrees that, in order to provide for the use of this Site, GOLFWEATHER contracts with certain vendors and service providers, which have certain rights, limitations of warranties, and limitations of liability in those contracts. Participant understands and agrees that it is not a third party beneficiary under any such agreements, that it has no rights whatsoever pursuant to such agreements, and that it has no contractual or other relationship with any advertiser, business affiliate, vendor or service provider by reason of the use or information provided on this Site or any agreement relating to the Site. To the extent that Participant has any such rights or claims by operation of law or otherwise, Participant hereby waives any and all rights and claims whatsoever against those vendors and service providers whether resulting from the exercise of any right by such vendors or service providers pursuant to such agreements, the any error or omission in the services provided, not provided, withdrawn or terminated, or the use of this Site.<br /><br /></li>
						<li><strong class="white">LIMITATION OF LIABILITY.</strong><br />GOLFWEATHER assumes no responsibility for, and shall not be liable for, any damages or expenses you may incur as a result of any inaccuracy, incompleteness or obsolescence of any Data contained in the Site. THE SERVICES OF THE SITE ARE PROVIDED .AS IS, WITH NO WARRANTIES WHATSOEVER. Without limiting the generality of the forgoing, you agree that neither GOLFWEATHER nor any of its affiliates, employees or agents will be liable to you or to any other party for any direct or indirect damages, or for any special, exemplary, punitive, incidental, consequential or other damages (including, but not limited to, lost profits or lost time), whether based on contract, tort, strict liability or otherwise, which arise out of or are in any way connected with any access to the Site or any viewing or use of any information on the Site. You acknowledge that the limitations in this Section are reasonable and appropriate. GOLFWEATHER DISCLAIMS ALL WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, CURRENCY OR RELIABILITY OF THE DATA IN THE SITE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OR OTHERWISE ARISING BY LAW OR STATUTE. YOU AGREE THAT YOUR USE OF, OR RELIANCE UPON, ALL DATA OBTAINED THROUGH THE SITE IS AT YOUR OWN DISCRETION AND RISK.<br /><br /></li>
						<li><strong class="white">INDEMNIFICATION</strong><br />You agree to indemnify and to hold GOLFWEATHER, its subsidiaries, affiliates, business partners, officers, employers and other agents, harmless from and against any loss, liability, damage or expense (including reasonable attorneys fees) arising out of your use of the Site, including, without limitation, any violations by you in the terms and conditions for your use of the Site.<br /><br /></li>
						<li><strong class="white">VIRUSES</strong><br />We will use commercially reasonable efforts to maintain the Site free of viruses and other harmful components. However, as the Site is accessible by third parties, we cannot assume any responsibility for any viruses or other harmful components that may affect your computer equipment or other property as a result of your access to, viewing of or downloading any Data from the Site. We do not warrant that the Site, its servers or any Data downloaded from the Site is free from viruses, bugs or other harmful components.<br /><br /></li>
						<li><strong class="white">MODIFICATIONS/TERMINATION</strong><br />Without limiting its other remedies, GOLFWEATHER may immediately discontinue, suspend, terminate or block your and any user's access to this Site at any time in its sole discretion. GOLFWEATHER may amend or modify these terms and conditions at any time. Any such changes will become effective immediately upon the date they are first posted to this Site. You agree to be bound by these revised terms and conditions. It is your responsibility to return to this page from time to time to review the most current terms and conditions. GOLFWEATHER does not assume any obligation to notify you of changes to these terms and conditions.<br /><br /></li>
						<li><strong class="white">ENTIRE AGREEMENT</strong><br />These terms and conditions of use for this website constitute the entire agreement between you and GOLFWEATHER regarding your access to the Site and your reproduction and use of any information in the Site. Any waiver of any term or condition shall not be effective unless in a written document signed by an authorized representative of GOLFWEATHER</li>
					</ol>
					
				</div>
		</div>
		<div class="mob-banner1 mt40">
			<a href=""><img src="<?php echo $dirAdj;?>img/banners/hero-8.jpg" class="banner_full" /></a>
		</div>
		<div class="mob-banner1 mt20 mb40">
			<img src="<?php echo $dirAdj;?>img/banners/ship-sticks.png" class="fw" />
		</div>
	</div>
</div>

<div class="botSpace"></div>
<?php
	require_once("includes/footer.php");
?>            

